###Crea un arreglo de 10 cincos

In [2]:
import numpy as np
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

###Crea un arreglo de enteros pares desde 10, inclusive, hasta 50, inclusive.

In [3]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

###Crea una matriz cuadrada de 4 por 4 de números enteros aleatorios.

In [6]:
np.random.randint(1, 100, (4, 4))

array([[15, 24, 47, 51],
       [44, 64, 22, 70],
       [91, 88, 44, 23],
       [14, 98, 62, 83]])

###Genera un arreglo de 10 números aleatorios entre 0 y 1 y calcula la suma de todos sus elementos.

In [12]:
array = np.random.rand(10)
float(array.sum())

3.9066694203046173

###Genera un arreglo de 10 números aleatorios entre 0 y 1 y calcula su media.

In [11]:
float(np.mean(array))

0.4904391871915571